name: 'Terraform'

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tfvars_file:
        description: 'Path to the .tfvars file'
        required: true
        default: 'terraform.tfvars'
      action:
        type: choice
        description: 'Terraform Action'
        options:
        - plan
        - apply
        - destroy
        required: true
        default: 'plan'

permissions:
  contents: read
  id-token: write   # Required for AWS credentials

jobs:
  Terraform-Action:
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        shell: bash
        working-directory: terraform
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.3

    - name: Initialize Terraform
      run: terraform init -upgrade

    - name: Terraform Plan
      run: terraform plan -var-file=${{ github.event.inputs.tfvars_file }} -out=tfplan

    - name: List Files (Debug)
      run: ls -la

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve tfplan

    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
      run: terraform destroy -auto-approve -var-file=${{ github.event.inputs.tfvars_file }}